### ISSUE TITLE
website not online

### ISSUE THREAD

**Issue by obaidazeino** [obaidazeino/accessible-content-for-all#1]
github acting strange and mixing between files of html validation fixes and accessible content for all when forking
also, website not online error 
@abhaysharma
@anna-pokhilenko

**Comment by abhaysharma** [comment]
@obaidazeino checking this repository now.

**Comment by abhaysharma** [comment]
@obaidazeino the website is live on GH Pages. I think you are having issue with the markbot.

**Comment by obaidazeino** [comment]
yeah just fixed the live issue with this, and need to fix the other errors.
however, my other repo "html indentaion fixes" is the one with persistant site not live issues
@abhaysharma

**Comment by abhaysharma** [comment]
@obaidazeino perfect! can you tag me in the other one and close this issue. Thanks!
